### ISSUE TITLE
Two small questions

### ISSUE THREAD

**Issue by colemickens** [gpyh/yarn#1]
1. Why does the 'profiles' directory live under devices, rather than as a top-level directory like you had previously?
2. What is the benefit of doing:

```
imports = [
  (import /home/gpyh/yarn "nicoletta")
];
```

vs

```
imports = [
  "/home/gpyh/yarn/devices/nicoletta"
];
```

**Comment by yacinehmito** [comment]
# Short answers
1. I didn't like the idea in the first place but it's awfully convenient, so I'm hiding it. As it is not formalized in the framework itself, feel free to move it up.
2. It has lots of small benefits, the first one being that it imports the whole framework (overridden packages, custom modules and the particular device module) in one go.

# Long answers

## First question

I didn't want to formalize the concept of a profile because I am not sold on it.

The more organizational notions you have,  the more complicated is the framework and the less freedom you have.

I feel that profiles are not that important because they are just abstract devices. You wouldn't always want to use one. I can see myself using a programmable module instead of a profile if two devices of the same kind would diverge enough.

Profiles can still live in a top-level directory if you want. You'll just need to add `../` when importing them.

What bugs me too is that there already exists a concept of "Nix profiles". I don't like this overlap.

## Second question

``` nix
# configuration.nix
{ ... }:

{
  imports = [
    "/home/gpyh/yarn/devices/nicoletta"
  ];
  # ...
}
```

This snippet imports a module given its path. Nix doesn't know a thing about what you mean by a device. It's the organization of folders that tells you that. 

Also, it only imports the device module. What about your packages and your other modules? You need to import them manually as well. You have three choices:
- Putting them in `configuration.nix`. It's what I was doing before. But the less I type in this file, the happier I am. And, the less I need to know about the folder structure, the more changes I can make without needing to modify the file.
- Putting them in the device module. This is the same problem as the one before. It's just located elsewhere. 
- Letting the yarn module do it for me. It ties everything together in only one place. Were I to change the framework structure, existing configuration wouldn't need to be changed.

What is the minimal amount of information you would need in `configuration.nix` to use the framework? 1) The location of the framework''s folder. 2) The device you are using. This is exactly what this snippet needs:

``` nix
# configuration.nix
{ ... }:

{
  imports = [
    (import /home/gpyh/yarn "nicoletta")
  ];
  # ...
}
```

Doing so acts as a safeguard: you can only import a device that has been declared in `all-devices.nix`. The redundancy prevents mistakes, but this technicality is hidden from you in default.nix`. Let's have a look at it:

``` nix
# This is a closure that takes the name of the device and returns a module.
deviceName:

{ config, pkgs, lib, ... }:

{
  imports = [
    # Importing the packages module that will override pkgs.
    ./packages
    # Importing the current device's module holding the system configuration.
    (import ./devices/all-devices.nix)."${deviceName}"
  ] ++ (import ./modules/module-list.nix); # Importing all the custom modules.
}
```

This is not a module. This is a higher order function as it returns a module.
The returned module imports the whole framework, but you wouldn't want to import devices that are irrelevant to the current one. So you pass the device name as parameter and it will look it up in `all-devices.nix`.
A side effect is that you can put your device module anywhere you want, as long as you have an entry in `all-devices.nix`. If you want to move `all-devices.nix`, you can do so as well by modifying the `default.nix` in the root folder. So, feel free to play with the structure.

Hit me up if you have any other question.

**Comment by colemickens** [comment]
Thank you for this very detailed explanation. I've learned a lot from this repo and this comment!

**Comment by yacinehmito** [comment]
:)
