### ISSUE TITLE
Upstream asciidoctor package

### ISSUE THREAD

**Issue by aneeshusa** [gpyh/yarn#2]
Writing a package for asciidoctor has been on my todo list for a long time, but I just found this repo and your version works great! Would you mind upstreaming it to the main nixpkgs repo?

**Comment by yacinehmito** [comment]
I still have a problem with it. When the package is installed, bundler becomes unusable. I'm having trouble finding out why.

Update:  
Apparently bundler ends up in the /bin folder of every package built using bundlerEnv, so this problem is not specific to this derivation. It should be fixed by rethinking how Ruby gems are packaged in Nix (which doesn't seem to be trivial at all).  
I'm submitting the package to nixpkgs (https://github.com/NixOS/nixpkgs/pull/15135)
